name: Github Registry

on: [push, pull_request, workflow_dispatch]

env:
  IMAGE_NAME: bernat13/miweb

jobs:
   build-and-push:
    name: build and push image
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    - name: build and push to docker
      uses: docker/build-push-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository:  ${{ env.IMAGE_NAME}}
        tag_with_ref: true
        tag_with_sha: true
        tags: ${{ github.sha }}
